### PR TITLE
warm up: remove vowels from sentence

### PR DESCRIPTION
**Pull request by deanjgoldman**

### CODE REVIEW

**Review by AnnaSula — COMMENTED** [review]
similar to my approach, nice

**Comment by isobelscott** [comment]
hi!! Love the input field - nice touch! 
The definition does get thrown off by duplicate vowels. 
This is what I entered and got
Enter a sentence: hi i'm a sentence with vooaels
h 'm  sntnc wth voels
it-usa-09475:Nov18th isobel$ ./warmupfunction.py
Enter a sentence: hi i'm a sentence with vooaels
h 'm  sntnc wth voels
it-usa-09475:Nov18th isobel$ ./warmupfunction.py
Enter a sentence: ooooo what's that?
oo wht's tht?

**Review by artopping — COMMENTED** [review]
Nice job! I like the input function too.

**Comment by isobelscott** [comment]
I was going to request changes :D
I think the double vowel thing might be fixed by adding an else: after -
+        if letter in vowels:
 +            sentence.remove(letter)

**Pull request merged**
